# Generated by Django 4.2.11 on 2024-08-15 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="course_code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="courseinstance",
            name="course_code",
            field=models.ForeignKey(
                db_column="course_code",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.course",
                to_field="course_code",
            ),
        ),
    ]
